apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: hydrabadi-restaurant
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-service.hydrabadi-restaurant.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"

  dashboard-provider.yaml: |
    apiVersion: 1
    providers:
      - name: HyderabadiRestaurant
        orgId: 1
        folder: "HyderabadiRestaurant"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
